name: "[collector] dev publish"

on:
  push:
    branches: ["dev"]

jobs:
  publish:
    environment: dev
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: collector
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Replace otel collector config file
        run: echo "${{ secrets.OTEL_COLLECTOR_CONFIG }}" > config.yaml
      - name: publish layer
        run: make publish-layer
